# Generated by Django 4.1.7 on 2025-03-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('word_count', models.PositiveIntegerField()),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.level')),
                ('topics', models.ManyToManyField(blank=True, to='common.topic')),
            ],
        ),
    ]
