/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './screens/**/*.{js,ts,jsx,tsx}',
    './Components/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        white: '#FFFFFF',
        black: '#292929',
        blue: {
          DEFAULT: '#2563EB',
          1: '#EFF6FF',
        },
        'blue-1': '#EFF6FF',
        'blue-light-1': '#3B82F6',
        'blue-light-2': '#60A5FA',
        'blue-light-3': '#93BBFD',
        'blue-light-4': '#BFDBFE',
        'blue-dark-1': '#1D4ED8',
        'blue-dark-2': '#1E40AF',
        'blue-dark-3': '#1E3A8A',
        'blue-dark-4': '#1E3A8A',
        'blue-dark-5': '#2563EB',
        orange: {
          DEFAULT: '#EF9949',
          1: '#FEF5ED',
        },
        'orange-1': '#FEF5ED',
        green: {
          DEFAULT: '#22C55E',
          1: '#EDFEF6',
        },
        'green-1': '#EDFEF6',
        'gray-dark': '#797777',
        gray: {
          DEFAULT: '#AAAAAA',
          1: '#656565',
        },
        'gray-1': '#656565',
        'gray-light': '#E2E2E2',
        'gray-light-1': '#F5F5F5',
        primary: '#2563EB',
        'red-dark-5': '#2563EB',
      },
      fontFamily: {},
      spacing: {
        1: '4px',
        2: '8px',
        2.5: '11px',
        3: '12px',
        4: '16px',
        5: '24px',
        6: '32px',
        7: '40px',
        8: '48px',
      },
      fontSize: {
        xs: '12px',
        sm: '14px',
        base: '16px',
        lg: '18px',
        xl: '20px',
        '2xl': '32px',
        '3xl': '40px',
      },
      lineHeight: {
        1: '18px',
        2: '21px',
        3: '24px',
        4: '27px',
        5: '30px',
        6: '48px',
        7: '60px',
      },
    },
  },
};
