# Generated by Django 4.1.7 on 2025-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('example', models.TextField()),
                ('usage_notes', models.TextField(blank=True)),
                ('vocabulary', models.ManyToManyField(blank=True, to='vocabulary.vocabulary')),
            ],
        ),
    ]
