# Generated by Django on 2025-01-01
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('vocabulary', '0001_initial'),
        ('account', '0001_initial'),
        ('sentence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentencestructure',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RenameField(
            model_name='sentencestructure',
            old_name='name',
            new_name='formula',
        ),
        migrations.RenameField(
            model_name='sentencestructure',
            old_name='usage_notes',
            new_name='example_sentence',
        ),
        migrations.RemoveField(
            model_name='sentencestructure',
            name='example',
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_created', to='account.account'),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='grammar_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='level',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.level'),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='pattern',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='topics',
            field=models.ManyToManyField(blank=True, to='common.topic'),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sentencestructure',
            name='updated_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sentence_updated', to='account.account'),
        ),
        migrations.CreateModel(
            name='SentenceVocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='sentence.sentencestructure')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
