# Generated by Django 5.0 on 2026-07-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_alter_sentencestructure_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencestructure',
            name='pattern',
            field=models.CharField(max_length=100),
        ),
    ]
