"""
Django settings for be project.
Generated by "django-admin startproject" using Django 5.0.
For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = (
    os.environ.get("SECRET_KEY")
    or os.environ.get("DJANGO_SECRET_KEY")
    or "django-insecure-dev-key"
)
DEBUG = os.environ.get("DEBUG", "True") == "True"
if not DEBUG and SECRET_KEY == "django-insecure-dev-key":
    raise ValueError(
        "Set SECRET_KEY or DJANGO_SECRET_KEY when DEBUG=False."
    )
ALLOWED_HOSTS = os.environ.get("ENV_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CORS_ALLOWED_ORIGINS = os.environ.get("ENV_ALLOWED_CORS", "http://localhost:8081").split(",")
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost(:[0-9]+)?$",
    r"^https?://127\.0\.0\.1(:[0-9]+)?$",
    r"^https?://10\.\d+\.\d+\.\d+(:[0-9]+)?$",
    r"^https?://192\.168\.\d+\.\d+(:[0-9]+)?$",
    r"^exp://.*$",
    r"^http://10\.\d+\.\d+\.\d+:\d+$",
    r"^https?://172\.(1[6-9]|2[0-9]|3[0-1])\.\d+\.\d+(:[0-9]+)?$",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework.authtoken",
    "rest_framework",
    "django_filters",
    "drf_yasg",
    "corsheaders",
    "account",
    "common",
    "listening",
    "reading",
    "lesson",
    "question",
    "sentence",
    "speaking",
    "vocabulary",
    "flashcard",
    "classroom",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "account.middleware.CurrentUserMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "common.mixins.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
}

ROOT_URLCONF = "be.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "be.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "account.Account"
if os.environ.get("BACKBLAZEB2_APP_KEY_ID"):
    DEFAULT_FILE_STORAGE = "b2_storage.storage.B2Storage"
else:
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"

BACKBLAZEB2_APP_KEY_ID = os.environ.get("BACKBLAZEB2_APP_KEY_ID")
BACKBLAZEB2_APP_KEY = os.environ.get("BACKBLAZEB2_APP_KEY")
BACKBLAZEB2_BUCKET_NAME = os.environ.get("BACKBLAZEB2_BUCKET_NAME")
BACKBLAZEB2_BUCKET_ID = os.environ.get("BACKBLAZEB2_BUCKET_ID")
BACKBLAZEB2_ACCOUNT_ID = os.environ.get("BACKBLAZEB2_ACCOUNT_ID")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

KEY_FCM = os.environ.get("KEY_FCM")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3001")

firebaseConfig = {
    "apiKey": os.environ.get("ApiKey"),
    "authDomain": os.environ.get("AuthDomain"),
    "databaseURL": os.environ.get("DatabaseURL"),
    "projectId": os.environ.get("ProjectId"),
    "storageBucket": os.environ.get("StorageBucket"),
    "messagingSenderId": os.environ.get("MessagingSenderId"),
    "appId": os.environ.get("AppId"),
    "measurementId": os.environ.get("MeasurementId"),
}
