# Generated by Django 4.1.7 on 2025-03-25 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listening', '0001_initial'),
        ('sentence', '0001_initial'),
        ('common', '0001_initial'),
        ('reading', '0001_initial'),
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.level')),
                ('listening_lessons', models.ManyToManyField(blank=True, to='listening.audiolesson')),
                ('reading_lessons', models.ManyToManyField(blank=True, to='reading.readinglesson')),
                ('sentences', models.ManyToManyField(blank=True, to='sentence.sentencestructure')),
                ('topics', models.ManyToManyField(blank=True, to='common.topic')),
                ('vocabulary', models.ManyToManyField(blank=True, to='vocabulary.vocabulary')),
            ],
        ),
    ]
